import type { Job, AtsSource } from '@/types/job';
import { isAIFromCurated } from './curatedAI';

interface GHJob {
  id: number;
  title: string;
  departments?: Array<{ name: string }>;
  offices?: Array<{ name: string }>;
  absolute_url?: string;
  updated_at?: string;
}

async function fetchGreenhouseJobs(slug: string, name: string, domain: string, batch?: string): Promise<Job[]> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 28000);
  try {
    const res = await fetch(`https://boards-api.greenhouse.io/v1/boards/${slug}/jobs?content=true`, {
      signal: controller.signal,
      next: { revalidate: 3600 },
    });
    if (!res.ok) return [];
    const data = await res.json() as { jobs?: GHJob[] };
    return (data.jobs ?? []).map(job => {
      const loc = job.offices?.[0]?.name ?? '';
      return {
        id: `gh-${slug}-${job.id}`,
        title: job.title,
        company: name,
        companyDomain: domain,
        location: loc,
        isRemote: loc.toLowerCase().includes('remote'),
        url: job.absolute_url ?? `https://boards.greenhouse.io/${slug}/jobs/${job.id}`,
        // updated_at is the last-modified date (Greenhouse public API doesn't expose original posting date)
        postedAt: job.updated_at ?? new Date(0).toISOString(),
        department: job.departments?.[0]?.name ?? '',
        ats: 'greenhouse' as AtsSource,
        sources: ['greenhouse' as AtsSource],
        isAI: isAIFromCurated(name),
        batch,
      };
    });
  } catch {
    return [];
  } finally {
    clearTimeout(timeout);
  }
}

const GREENHOUSE_COMPANIES: Array<{ slug: string; name: string; domain: string; batch?: string }> = [
  // AI / ML
  { slug: 'openai', name: 'OpenAI', domain: 'openai.com', batch: 'W16' },
  { slug: 'anthropic', name: 'Anthropic', domain: 'anthropic.com', batch: 'S21' },
  { slug: 'deepmind', name: 'Google DeepMind', domain: 'deepmind.com' },
  { slug: 'scaleai', name: 'Scale AI', domain: 'scale.com', batch: 'S16' },
  { slug: 'coreweave', name: 'CoreWeave', domain: 'coreweave.com', batch: 'S19' },
  { slug: 'xai', name: 'xAI', domain: 'x.ai' },
  { slug: 'cohere', name: 'Cohere', domain: 'cohere.com' },
  { slug: 'stability', name: 'Stability AI', domain: 'stability.ai' },
  { slug: 'abridge', name: 'Abridge', domain: 'abridge.com' },
  { slug: 'arizeai', name: 'Arize AI', domain: 'arize.com' },
  { slug: 'twelve-labs', name: 'Twelve Labs', domain: 'twelvelabs.io' },
  { slug: 'fireworks-ai', name: 'Fireworks AI', domain: 'fireworks.ai' },
  // Big Tech
  { slug: 'netflix', name: 'Netflix', domain: 'netflix.com' },
  { slug: 'spotify', name: 'Spotify', domain: 'spotify.com' },
  { slug: 'airbnb', name: 'Airbnb', domain: 'airbnb.com' },
  { slug: 'twitch', name: 'Twitch', domain: 'twitch.tv' },
  { slug: 'figma', name: 'Figma', domain: 'figma.com', batch: 'W15' },
  { slug: 'dropbox', name: 'Dropbox', domain: 'dropbox.com' },
  { slug: 'pinterest', name: 'Pinterest', domain: 'pinterest.com', batch: 'W10' },
  { slug: 'reddit', name: 'Reddit', domain: 'reddit.com', batch: 'Y05' },
  { slug: 'etsy', name: 'Etsy', domain: 'etsy.com' },
  { slug: 'duolingo', name: 'Duolingo', domain: 'duolingo.com', batch: 'W12' },
  // Fintech
  { slug: 'stripe', name: 'Stripe', domain: 'stripe.com', batch: 'S09' },
  { slug: 'robinhood', name: 'Robinhood', domain: 'robinhood.com', batch: 'W13' },
  { slug: 'lyft', name: 'Lyft', domain: 'lyft.com', batch: 'S11' },
  { slug: 'coinbase', name: 'Coinbase', domain: 'coinbase.com', batch: 'S12' },
  { slug: 'chime', name: 'Chime', domain: 'chime.com', batch: 'S14' },
  { slug: 'gusto', name: 'Gusto', domain: 'gusto.com', batch: 'W12' },
  { slug: 'faire', name: 'Faire', domain: 'faire.com', batch: 'W17' },
  { slug: 'klarna', name: 'Klarna', domain: 'klarna.com' },
  { slug: 'plaid', name: 'Plaid', domain: 'plaid.com' },
  { slug: 'brex', name: 'Brex', domain: 'brex.com', batch: 'W17' },
  { slug: 'affirm', name: 'Affirm', domain: 'affirm.com' },
  { slug: 'marqeta', name: 'Marqeta', domain: 'marqeta.com' },
  // SaaS / B2B
  { slug: 'datadog', name: 'Datadog', domain: 'datadoghq.com', batch: 'S10' },
  { slug: 'okta', name: 'Okta', domain: 'okta.com', batch: 'S09' },
  { slug: 'klaviyo', name: 'Klaviyo', domain: 'klaviyo.com', batch: 'S12' },
  { slug: 'snowflake', name: 'Snowflake', domain: 'snowflake.com', batch: 'S12' },
  { slug: 'databricks', name: 'Databricks', domain: 'databricks.com', batch: 'S13' },
  { slug: 'gong', name: 'Gong', domain: 'gong.io', batch: 'S16' },
  { slug: 'braze', name: 'Braze', domain: 'braze.com' },
  { slug: 'airtable', name: 'Airtable', domain: 'airtable.com' },
  { slug: 'asana', name: 'Asana', domain: 'asana.com' },
  { slug: 'hightouch', name: 'Hightouch', domain: 'hightouch.com', batch: 'W19' },
  { slug: 'bloomreach', name: 'Bloomreach', domain: 'bloomreach.com', batch: 'W09' },
  { slug: 'benchling', name: 'Benchling', domain: 'benchling.com', batch: 'S12' },
  { slug: 'squarespace', name: 'Squarespace', domain: 'squarespace.com' },
  { slug: 'palantir', name: 'Palantir', domain: 'palantir.com' },
  { slug: 'waymo', name: 'Waymo', domain: 'waymo.com' },
  { slug: 'canva', name: 'Canva', domain: 'canva.com' },
  { slug: 'hubspot', name: 'HubSpot', domain: 'hubspot.com' },
  { slug: 'zendesk', name: 'Zendesk', domain: 'zendesk.com' },
  { slug: 'mongodb', name: 'MongoDB', domain: 'mongodb.com' },
  { slug: 'hashicorp', name: 'HashiCorp', domain: 'hashicorp.com' },
  { slug: 'confluent', name: 'Confluent', domain: 'confluent.io' },
  { slug: 'twilio', name: 'Twilio', domain: 'twilio.com' },
  { slug: 'sendgrid', name: 'SendGrid', domain: 'sendgrid.com' },
  { slug: 'pagerduty', name: 'PagerDuty', domain: 'pagerduty.com' },
  { slug: 'elastic', name: 'Elastic', domain: 'elastic.co' },
  { slug: 'docusign', name: 'DocuSign', domain: 'docusign.com' },
  { slug: 'veeva', name: 'Veeva Systems', domain: 'veeva.com' },
  { slug: 'amplitude', name: 'Amplitude', domain: 'amplitude.com' },
  { slug: 'mixpanel', name: 'Mixpanel', domain: 'mixpanel.com' },
  { slug: 'segment', name: 'Segment', domain: 'segment.com' },
  { slug: 'heap', name: 'Heap', domain: 'heap.io' },
  { slug: 'fullstory', name: 'FullStory', domain: 'fullstory.com' },
  { slug: 'contentsquare', name: 'Contentsquare', domain: 'contentsquare.com' },
  { slug: 'doordash', name: 'DoorDash', domain: 'doordash.com', batch: 'S13' },
  { slug: 'instacart', name: 'Instacart', domain: 'instacart.com', batch: 'S12' },
  // Design / Creative tools
  { slug: 'invision', name: 'InVision', domain: 'invisionapp.com' },
  { slug: 'abstract', name: 'Abstract', domain: 'abstract.com' },
  { slug: 'zeplin', name: 'Zeplin', domain: 'zeplin.io' },
  // Automotive / Robotics
  { slug: 'figure', name: 'Figure AI', domain: 'figure.ai' },
  { slug: 'nuro', name: 'Nuro', domain: 'nuro.ai' },
  // Media / Gaming
  { slug: 'roblox', name: 'Roblox', domain: 'roblox.com' },
  { slug: 'unity', name: 'Unity', domain: 'unity.com' },
  { slug: 'epic', name: 'Epic Games', domain: 'epicgames.com' },
  { slug: 'vimeo', name: 'Vimeo', domain: 'vimeo.com' },
  // E-commerce / Retail
  { slug: 'shopify', name: 'Shopify', domain: 'shopify.com' },
  { slug: 'wayfair', name: 'Wayfair', domain: 'wayfair.com' },
  // Health
  { slug: 'tempus', name: 'Tempus', domain: 'tempus.com' },
  { slug: 'optum', name: 'Optum', domain: 'optum.com' },
  // Security
  { slug: 'crowdstrike', name: 'CrowdStrike', domain: 'crowdstrike.com' },
  { slug: 'snyk', name: 'Snyk', domain: 'snyk.io' },
  { slug: 'lacework', name: 'Lacework', domain: 'lacework.com' },
  { slug: 'semgrep', name: 'Semgrep', domain: 'semgrep.dev' },
  // Education
  { slug: 'coursera', name: 'Coursera', domain: 'coursera.org' },
  { slug: 'brilliant', name: 'Brilliant', domain: 'brilliant.org' },
  // Productivity / Collaboration (new)
  { slug: 'notionhq', name: 'Notion', domain: 'notion.so' },
  { slug: 'slack', name: 'Slack', domain: 'slack.com' },
  { slug: 'gitlab', name: 'GitLab', domain: 'gitlab.com' },
  { slug: 'monday', name: 'monday.com', domain: 'monday.com' },
  { slug: 'box', name: 'Box', domain: 'box.com' },
  { slug: 'zoom', name: 'Zoom', domain: 'zoom.us' },
  { slug: 'lucid', name: 'Lucidchart', domain: 'lucid.co' },
  { slug: 'miro', name: 'Miro', domain: 'miro.com' },
  { slug: 'atlassian', name: 'Atlassian', domain: 'atlassian.com' },
  // Dev Tools / Infra (new)
  { slug: 'launchdarkly', name: 'LaunchDarkly', domain: 'launchdarkly.com', batch: 'S14' },
  { slug: 'newrelic', name: 'New Relic', domain: 'newrelic.com' },
  { slug: 'splunk', name: 'Splunk', domain: 'splunk.com' },
  { slug: 'fastly', name: 'Fastly', domain: 'fastly.com' },
  { slug: 'jetbrains', name: 'JetBrains', domain: 'jetbrains.com' },
  { slug: '1password', name: '1Password', domain: '1password.com' },
  { slug: 'sentry', name: 'Sentry', domain: 'sentry.io', batch: 'W12' },
  { slug: 'digitalocean', name: 'DigitalOcean', domain: 'digitalocean.com' },
  { slug: 'cloudflare', name: 'Cloudflare', domain: 'cloudflare.com' },
  // AI / ML (new)
  { slug: 'midjourney', name: 'Midjourney', domain: 'midjourney.com' },
  { slug: 'adept', name: 'Adept', domain: 'adept.ai' },
  { slug: 'characterai', name: 'Character.AI', domain: 'character.ai' },
  { slug: 'inflection-ai', name: 'Inflection AI', domain: 'inflection.ai' },
  { slug: 'huggingface', name: 'Hugging Face', domain: 'huggingface.co' },
  { slug: 'mistral', name: 'Mistral AI', domain: 'mistral.ai' },
  // Fintech (new)
  { slug: 'wise', name: 'Wise', domain: 'wise.com' },
  { slug: 'nubank', name: 'Nubank', domain: 'nubank.com.br' },
  { slug: 'revolut', name: 'Revolut', domain: 'revolut.com' },
  { slug: 'monzo', name: 'Monzo', domain: 'monzo.com' },
  { slug: 'sofi', name: 'SoFi', domain: 'sofi.com' },
  { slug: 'nerdwallet', name: 'NerdWallet', domain: 'nerdwallet.com' },
  { slug: 'navan', name: 'Navan', domain: 'navan.com' },
  { slug: 'creditkarma', name: 'Credit Karma', domain: 'creditkarma.com' },
  { slug: 'acorns', name: 'Acorns', domain: 'acorns.com' },
  // HR Tech (new)
  { slug: 'culture-amp', name: 'Culture Amp', domain: 'cultureamp.com' },
  { slug: 'leapsome', name: 'Leapsome', domain: 'leapsome.com' },
  { slug: 'personio', name: 'Personio', domain: 'personio.com' },
  { slug: 'hibob', name: 'HiBob', domain: 'hibob.com' },
  // Gaming / Entertainment (new)
  { slug: 'riotgames', name: 'Riot Games', domain: 'riotgames.com' },
  { slug: 'niantic', name: 'Niantic', domain: 'nianticlabs.com' },
  { slug: 'zynga', name: 'Zynga', domain: 'zynga.com' },
  { slug: 'kabam', name: 'Kabam', domain: 'kabam.com' },
  { slug: 'scopely', name: 'Scopely', domain: 'scopely.com' },
  { slug: 'peloton', name: 'Peloton', domain: 'onepeloton.com' },
  { slug: 'eventbrite', name: 'Eventbrite', domain: 'eventbrite.com' },
  { slug: 'fanduel', name: 'FanDuel', domain: 'fanduel.com' },
  { slug: 'draftkings', name: 'DraftKings', domain: 'draftkings.com' },
  // E-commerce / Retail (new)
  { slug: 'poshmark', name: 'Poshmark', domain: 'poshmark.com' },
  { slug: 'chewy', name: 'Chewy', domain: 'chewy.com' },
  { slug: 'carvana', name: 'Carvana', domain: 'carvana.com' },
  { slug: 'grubhub', name: 'Grubhub', domain: 'grubhub.com' },
  { slug: 'toast', name: 'Toast', domain: 'toasttab.com' },
  { slug: 'olo', name: 'Olo', domain: 'olo.com' },
  { slug: 'gopuff', name: 'GoPuff', domain: 'gopuff.com' },
  // Health (new)
  { slug: 'oscar', name: 'Oscar Health', domain: 'hioscar.com' },
  { slug: 'modernhealth', name: 'Modern Health', domain: 'modernhealth.com' },
  { slug: 'noom', name: 'Noom', domain: 'noom.com' },
  { slug: 'cerebral', name: 'Cerebral', domain: 'cerebral.com' },
  // Real Estate / Travel (new)
  { slug: 'opendoor', name: 'Opendoor', domain: 'opendoor.com' },
  { slug: 'compass', name: 'Compass', domain: 'compass.com' },
  { slug: 'redfin', name: 'Redfin', domain: 'redfin.com' },
  { slug: 'hopper', name: 'Hopper', domain: 'hopper.com' },
  // Analytics / Marketing (new)
  { slug: 'usertesting', name: 'UserTesting', domain: 'usertesting.com' },
  { slug: 'sprinklr', name: 'Sprinklr', domain: 'sprinklr.com' },
  { slug: 'hotjar', name: 'Hotjar', domain: 'hotjar.com' },
  { slug: 'productboard', name: 'Productboard', domain: 'productboard.com' },
  // Education (new)
  { slug: 'udemy', name: 'Udemy', domain: 'udemy.com' },
  { slug: 'chegg', name: 'Chegg', domain: 'chegg.com' },
  { slug: 'pluralsight', name: 'Pluralsight', domain: 'pluralsight.com' },
  { slug: 'khanacademy', name: 'Khan Academy', domain: 'khanacademy.org' },
  { slug: 'duolingo', name: 'Duolingo', domain: 'duolingo.com' },
  // Security (new wave)
  { slug: 'wiz-inc', name: 'Wiz', domain: 'wiz.io' },
  { slug: 'orca-security', name: 'Orca Security', domain: 'orca.security' },
  { slug: 'jfrog', name: 'JFrog', domain: 'jfrog.com' },
  { slug: 'checkmarx', name: 'Checkmarx', domain: 'checkmarx.com' },
  { slug: 'sonatype', name: 'Sonatype', domain: 'sonatype.com' },
  { slug: 'sailpoint', name: 'SailPoint', domain: 'sailpoint.com' },
  { slug: 'cyberark', name: 'CyberArk', domain: 'cyberark.com' },
  { slug: 'sysdig', name: 'Sysdig', domain: 'sysdig.com' },
  { slug: 'cribl', name: 'Cribl', domain: 'cribl.io' },
  { slug: 'exabeam', name: 'Exabeam', domain: 'exabeam.com' },
  { slug: 'abnormalsecurity', name: 'Abnormal Security', domain: 'abnormalsecurity.com' },
  { slug: 'huntress', name: 'Huntress', domain: 'huntress.com' },
  { slug: 'expel', name: 'Expel', domain: 'expel.io' },
  { slug: 'tanium', name: 'Tanium', domain: 'tanium.com' },
  { slug: 'illumio', name: 'Illumio', domain: 'illumio.com' },
  { slug: 'rapid7', name: 'Rapid7', domain: 'rapid7.com' },
  { slug: 'qualys', name: 'Qualys', domain: 'qualys.com' },
  { slug: 'tenable', name: 'Tenable', domain: 'tenable.com' },
  { slug: 'darktrace', name: 'Darktrace', domain: 'darktrace.com' },
  { slug: 'sentinelone', name: 'SentinelOne', domain: 'sentinelone.com' },
  { slug: 'vectra-ai', name: 'Vectra AI', domain: 'vectra.ai' },
  { slug: 'logrhythm', name: 'LogRhythm', domain: 'logrhythm.com' },
  { slug: 'secureworks', name: 'Secureworks', domain: 'secureworks.com' },
  { slug: 'arcticwolf', name: 'Arctic Wolf', domain: 'arcticwolf.com' },
  // Data / Analytics (new wave)
  { slug: 'dbtlabs', name: 'dbt Labs', domain: 'getdbt.com' },
  { slug: 'airbyte', name: 'Airbyte', domain: 'airbyte.com' },
  { slug: 'thoughtspot', name: 'ThoughtSpot', domain: 'thoughtspot.com' },
  { slug: 'domo', name: 'Domo', domain: 'domo.com' },
  { slug: 'modeanalytics', name: 'Mode', domain: 'mode.com' },
  { slug: 'honeycomb-io', name: 'Honeycomb', domain: 'honeycomb.io' },
  { slug: 'chronosphere', name: 'Chronosphere', domain: 'chronosphere.io' },
  { slug: 'clickhouse', name: 'ClickHouse', domain: 'clickhouse.com' },
  { slug: 'timescale', name: 'Timescale', domain: 'timescale.com' },
  { slug: 'rudderstack', name: 'RudderStack', domain: 'rudderstack.com' },
  { slug: 'mparticle', name: 'mParticle', domain: 'mparticle.com' },
  { slug: 'tealium', name: 'Tealium', domain: 'tealium.com' },
  { slug: 'amperity', name: 'Amperity', domain: 'amperity.com' },
  { slug: 'sisense', name: 'Sisense', domain: 'sisense.com' },
  { slug: 'atlan', name: 'Atlan', domain: 'atlan.com' },
  { slug: 'alation', name: 'Alation', domain: 'alation.com' },
  { slug: 'collibra', name: 'Collibra', domain: 'collibra.com' },
  { slug: 'informatica', name: 'Informatica', domain: 'informatica.com' },
  { slug: 'starburst', name: 'Starburst', domain: 'starburst.io' },
  { slug: 'imply', name: 'Imply', domain: 'imply.io' },
  { slug: 'rockset', name: 'Rockset', domain: 'rockset.com' },
  { slug: 'iterable', name: 'Iterable', domain: 'iterable.com' },
  { slug: 'customer-io', name: 'Customer.io', domain: 'customer.io' },
  { slug: 'attentive', name: 'Attentive', domain: 'attentive.com' },
  // HR Tech (new wave)
  { slug: 'justworks', name: 'Justworks', domain: 'justworks.com' },
  { slug: 'namely', name: 'Namely', domain: 'namely.com' },
  { slug: 'homebase', name: 'Homebase', domain: 'joinhomebase.com' },
  { slug: 'deputy', name: 'Deputy', domain: 'deputy.com' },
  { slug: 'factorialhr', name: 'Factorial', domain: 'factorialhr.com' },
  { slug: 'oysterhr', name: 'Oyster HR', domain: 'oysterhr.com' },
  { slug: 'multiplierhq', name: 'Multiplier', domain: 'multiplier.com' },
  { slug: 'bamboohr', name: 'BambooHR', domain: 'bamboohr.com' },
  { slug: 'paycor', name: 'Paycor', domain: 'paycor.com' },
  { slug: 'trinet', name: 'TriNet', domain: 'trinet.com' },
  { slug: 'workable', name: 'Workable', domain: 'workable.com' },
  // Legal Tech
  { slug: 'ironclad', name: 'Ironclad', domain: 'ironcladapp.com' },
  { slug: 'clio', name: 'Clio', domain: 'clio.com' },
  { slug: 'pandadoc', name: 'PandaDoc', domain: 'pandadoc.com' },
  { slug: 'disco', name: 'DISCO', domain: 'csdisco.com' },
  { slug: 'legalzoom', name: 'LegalZoom', domain: 'legalzoom.com' },
  { slug: 'evisort', name: 'Evisort', domain: 'evisort.com' },
  { slug: 'linksquares', name: 'LinkSquares', domain: 'linksquares.com' },
  { slug: 'contractbook', name: 'ContractBook', domain: 'contractbook.com' },
  { slug: 'spotdraft', name: 'SpotDraft', domain: 'spotdraft.com' },
  { slug: 'juro', name: 'Juro', domain: 'juro.com' },
  { slug: 'lexion', name: 'Lexion', domain: 'lexion.ai' },
  // PropTech
  { slug: 'zillow', name: 'Zillow', domain: 'zillow.com' },
  { slug: 'better', name: 'Better.com', domain: 'better.com' },
  { slug: 'homelight', name: 'HomeLight', domain: 'homelight.com' },
  { slug: 'blend', name: 'Blend Labs', domain: 'blend.com' },
  { slug: 'divvyhomes', name: 'Divvy Homes', domain: 'divvyhomes.com' },
  { slug: 'orchard', name: 'Orchard', domain: 'orchard.com' },
  { slug: 'offerpad', name: 'Offerpad', domain: 'offerpad.com' },
  { slug: 'costar', name: 'CoStar', domain: 'costar.com' },
  { slug: 'wework', name: 'WeWork', domain: 'wework.com' },
  { slug: 'sonder', name: 'Sonder', domain: 'sonder.com' },
  // Health Tech (new wave)
  { slug: 'teladoc', name: 'Teladoc Health', domain: 'teladochealth.com' },
  { slug: 'swordhealth', name: 'Sword Health', domain: 'swordhealth.com' },
  { slug: 'helloalma', name: 'Alma', domain: 'helloalma.com' },
  { slug: 'growtherapy', name: 'Grow Therapy', domain: 'growtherapy.com' },
  { slug: 'simplepractice', name: 'SimplePractice', domain: 'simplepractice.com' },
  { slug: 'flatironhealth', name: 'Flatiron Health', domain: 'flatiron.com' },
  { slug: 'guardanthealth', name: 'Guardant Health', domain: 'guardanthealth.com' },
  { slug: 'recursion', name: 'Recursion', domain: 'recursion.com' },
  { slug: 'invitae', name: 'Invitae', domain: 'invitae.com' },
  { slug: 'athenahealth', name: 'athenahealth', domain: 'athenahealth.com' },
  { slug: 'tebra', name: 'Tebra', domain: 'tebra.com' },
  { slug: 'accolade', name: 'Accolade', domain: 'accolade.com' },
  { slug: 'transcarent', name: 'Transcarent', domain: 'transcarent.com' },
  { slug: 'exactsciences', name: 'Exact Sciences', domain: 'exactsciences.com' },
  { slug: 'evolenthealth', name: 'Evolent Health', domain: 'evolenthealth.com' },
  { slug: 'veracyte', name: 'Veracyte', domain: 'veracyte.com' },
  // FinTech / Crypto / InsurTech (new wave)
  { slug: 'kraken', name: 'Kraken', domain: 'kraken.com' },
  { slug: 'gemini', name: 'Gemini', domain: 'gemini.com' },
  { slug: 'alchemy', name: 'Alchemy', domain: 'alchemy.com' },
  { slug: 'opensea', name: 'OpenSea', domain: 'opensea.io' },
  { slug: 'lemonade', name: 'Lemonade', domain: 'lemonade.com' },
  { slug: 'rootinsurance', name: 'Root Insurance', domain: 'joinroot.com' },
  { slug: 'hippo', name: 'Hippo', domain: 'hippo.com' },
  { slug: 'clearcover', name: 'Clearcover', domain: 'clearcover.com' },
  { slug: 'ethos', name: 'Ethos Life', domain: 'ethoslife.com' },
  { slug: 'policygenius', name: 'PolicyGenius', domain: 'policygenius.com' },
  { slug: 'albert', name: 'Albert', domain: 'albert.com' },
  { slug: 'cleo', name: 'Cleo', domain: 'meetcleo.com' },
  { slug: 'moneylion', name: 'MoneyLion', domain: 'moneylion.com' },
  { slug: 'step', name: 'Step', domain: 'step.com' },
  { slug: 'current', name: 'Current', domain: 'current.com' },
  { slug: 'varo', name: 'Varo', domain: 'varomoney.com' },
  { slug: 'ladder', name: 'Ladder', domain: 'ladderlife.com' },
  { slug: 'bestow', name: 'Bestow', domain: 'bestow.com' },
  { slug: 'kin', name: 'Kin Insurance', domain: 'kin.com' },
  { slug: 'metromile', name: 'Metromile', domain: 'metromile.com' },
  // E-commerce / Fashion / Resale
  { slug: 'reverb', name: 'Reverb', domain: 'reverb.com' },
  { slug: 'mercari', name: 'Mercari', domain: 'mercari.com' },
  { slug: 'offerup', name: 'OfferUp', domain: 'offerup.com' },
  { slug: 'thredup', name: 'thredUp', domain: 'thredup.com' },
  { slug: 'whatnot', name: 'Whatnot', domain: 'whatnot.com' },
  { slug: 'grailed', name: 'Grailed', domain: 'grailed.com' },
  { slug: 'vestiairecollective', name: 'Vestiaire Collective', domain: 'vestiairecollective.com' },
  { slug: 'farfetch', name: 'Farfetch', domain: 'farfetch.com' },
  { slug: 'renttherunway', name: 'Rent the Runway', domain: 'renttherunway.com' },
  { slug: 'stitchfix', name: 'Stitch Fix', domain: 'stitchfix.com' },
  { slug: 'warbyparker', name: 'Warby Parker', domain: 'warbyparker.com' },
  { slug: 'allbirds', name: 'Allbirds', domain: 'allbirds.com' },
  { slug: 'everlane', name: 'Everlane', domain: 'everlane.com' },
  { slug: 'bonobos', name: 'Bonobos', domain: 'bonobos.com' },
  { slug: 'awaytravel', name: 'Away', domain: 'awaytravel.com' },
  // Food / Delivery (new wave)
  { slug: 'thrivemarket', name: 'Thrive Market', domain: 'thrivemarket.com' },
  { slug: 'freshly', name: 'Freshly', domain: 'freshly.com' },
  { slug: 'dailyharvest', name: 'Daily Harvest', domain: 'daily-harvest.com' },
  { slug: 'misfitsmarket', name: 'Misfits Market', domain: 'misfitsmarket.com' },
  { slug: 'deliveroo', name: 'Deliveroo', domain: 'deliveroo.com' },
  { slug: 'getir', name: 'Getir', domain: 'getir.com' },
  { slug: 'flink', name: 'Flink', domain: 'goflink.com' },
  { slug: 'sweetgreen', name: 'Sweetgreen', domain: 'sweetgreen.com' },
  // Gaming (new wave)
  { slug: 'bungie', name: 'Bungie', domain: 'bungie.net' },
  { slug: 'jamcity', name: 'Jam City', domain: 'jamcity.com' },
  { slug: 'playtika', name: 'Playtika', domain: 'playtika.com' },
  { slug: 'moonactive', name: 'Moon Active', domain: 'moonactive.com' },
  { slug: 'tilting-point', name: 'Tilting Point', domain: 'tiltingpoint.com' },
  { slug: 'bigfishgames', name: 'Big Fish Games', domain: 'bigfishgames.com' },
  { slug: 'glu', name: 'Glu Mobile', domain: 'glu.com' },
  { slug: 'rovio', name: 'Rovio', domain: 'rovio.com' },
  { slug: 'supercell', name: 'Supercell', domain: 'supercell.com' },
  // Travel / Hospitality (new wave)
  { slug: 'turo', name: 'Turo', domain: 'turo.com' },
  { slug: 'vacasa', name: 'Vacasa', domain: 'vacasa.com' },
  { slug: 'getaround', name: 'Getaround', domain: 'getaround.com' },
  { slug: 'omio', name: 'Omio', domain: 'omio.com' },
  { slug: 'flixbus', name: 'FlixBus', domain: 'flixbus.com' },
  { slug: 'outdoorsy', name: 'Outdoorsy', domain: 'outdoorsy.com' },
  { slug: 'selina', name: 'Selina', domain: 'selina.com' },
  { slug: 'spotnana', name: 'Spotnana', domain: 'spotnana.com' },
  { slug: 'tripadvisor', name: 'Tripadvisor', domain: 'tripadvisor.com' },
  // Logistics / Supply Chain
  { slug: 'flexport', name: 'Flexport', domain: 'flexport.com' },
  { slug: 'shipbob', name: 'ShipBob', domain: 'shipbob.com' },
  { slug: 'stord', name: 'Stord', domain: 'stord.com' },
  { slug: 'narvar', name: 'Narvar', domain: 'narvar.com' },
  { slug: 'shippo', name: 'Shippo', domain: 'goshippo.com' },
  { slug: 'easypost', name: 'EasyPost', domain: 'easypost.com' },
  { slug: 'project44', name: 'project44', domain: 'project44.com' },
  { slug: 'fourkites', name: 'FourKites', domain: 'fourkites.com' },
  { slug: 'convoy', name: 'Convoy', domain: 'convoy.com' },
  { slug: 'loopcommerce', name: 'Loop Returns', domain: 'loopreturns.com' },
  // Marketing Tech / Sales Intelligence
  { slug: 'salesloft', name: 'Salesloft', domain: 'salesloft.com' },
  { slug: 'outreach', name: 'Outreach', domain: 'outreach.io' },
  { slug: 'apolloio', name: 'Apollo.io', domain: 'apollo.io' },
  { slug: 'zoominfo', name: 'ZoomInfo', domain: 'zoominfo.com' },
  { slug: 'demandbase', name: 'Demandbase', domain: 'demandbase.com' },
  { slug: '6sense', name: '6sense', domain: '6sense.com' },
  { slug: 'clari', name: 'Clari', domain: 'clari.com' },
  { slug: 'seismic', name: 'Seismic', domain: 'seismic.com' },
  { slug: 'highspot', name: 'Highspot', domain: 'highspot.com' },
  { slug: 'showpad', name: 'Showpad', domain: 'showpad.com' },
  { slug: 'mindtickle', name: 'Mindtickle', domain: 'mindtickle.com' },
  { slug: 'drift', name: 'Drift', domain: 'drift.com' },
  { slug: 'qualified', name: 'Qualified', domain: 'qualified.com' },
  { slug: 'clearbit', name: 'Clearbit', domain: 'clearbit.com' },
  { slug: 'bombora', name: 'Bombora', domain: 'bombora.com' },
  { slug: 'mutiny', name: 'Mutiny', domain: 'mutinyhq.com' },
  // Developer Tools (new wave)
  { slug: 'postman', name: 'Postman', domain: 'postman.com' },
  { slug: 'readme', name: 'ReadMe', domain: 'readme.com' },
  { slug: 'kong', name: 'Kong', domain: 'konghq.com' },
  { slug: 'circleci', name: 'CircleCI', domain: 'circleci.com' },
  { slug: 'harness', name: 'Harness', domain: 'harness.io' },
  { slug: 'buildkite', name: 'Buildkite', domain: 'buildkite.com' },
  { slug: 'ably', name: 'Ably', domain: 'ably.com' },
  { slug: 'livekit', name: 'LiveKit', domain: 'livekit.io' },
  { slug: 'novu', name: 'Novu', domain: 'novu.co' },
  { slug: 'courier', name: 'Courier', domain: 'courier.com' },
  // Automotive / Mobility / Aerospace
  { slug: 'rivian', name: 'Rivian', domain: 'rivian.com' },
  { slug: 'lucidmotors', name: 'Lucid Motors', domain: 'lucidmotors.com' },
  { slug: 'jobyaviation', name: 'Joby Aviation', domain: 'jobyaviation.com' },
  { slug: 'archeraviation', name: 'Archer Aviation', domain: 'archer.com' },
  { slug: 'wiskaero', name: 'Wisk Aero', domain: 'wisk.aero' },
  { slug: 'zoox', name: 'Zoox', domain: 'zoox.com' },
  { slug: 'aurora', name: 'Aurora Innovation', domain: 'aurora.tech' },
  { slug: 'motional', name: 'Motional', domain: 'motional.com' },
  { slug: 'wayve', name: 'Wayve', domain: 'wayve.ai' },
  { slug: 'cruise', name: 'Cruise', domain: 'getcruise.com' },
  // Climate Tech
  { slug: 'watershed', name: 'Watershed', domain: 'watershed.com' },
  { slug: 'tomorrow', name: 'Tomorrow.io', domain: 'tomorrow.io' },
  { slug: 'arcadia', name: 'Arcadia', domain: 'arcadia.com' },
  { slug: 'helion', name: 'Helion Energy', domain: 'helionenergy.com' },
  { slug: 'samsara', name: 'Samsara', domain: 'samsara.com' },
  { slug: 'formenergy', name: 'Form Energy', domain: 'formenergy.com' },
  { slug: 'sunrun', name: 'Sunrun', domain: 'sunrun.com' },
  // Media / Content
  { slug: 'buzzfeed', name: 'BuzzFeed', domain: 'buzzfeed.com' },
  { slug: 'voxmedia', name: 'Vox Media', domain: 'voxmedia.com' },
  { slug: 'theathleticmedia', name: 'The Athletic', domain: 'theathletic.com' },
  { slug: 'medium', name: 'Medium', domain: 'medium.com' },
  { slug: 'axios', name: 'Axios', domain: 'axios.com' },
  { slug: 'morningbrew', name: 'Morning Brew', domain: 'morningbrew.com' },
  { slug: 'complexnetworks', name: 'Complex Networks', domain: 'complex.com' },
  // Ad Tech
  { slug: 'thetradedesk', name: 'The Trade Desk', domain: 'thetradedesk.com' },
  { slug: 'moloco', name: 'Moloco', domain: 'moloco.com' },
  { slug: 'liftoff', name: 'Liftoff', domain: 'liftoff.io' },
  { slug: 'applovin', name: 'AppLovin', domain: 'applovin.com' },
  { slug: 'digital-turbine', name: 'Digital Turbine', domain: 'digitalturbine.com' },
  // CRM / Customer Success
  { slug: 'pipedrive', name: 'Pipedrive', domain: 'pipedrive.com' },
  { slug: 'kustomer', name: 'Kustomer', domain: 'kustomer.com' },
  { slug: 'gladly', name: 'Gladly', domain: 'gladly.com' },
  { slug: 'gorgias', name: 'Gorgias', domain: 'gorgias.com' },
  { slug: 'gainsight', name: 'Gainsight', domain: 'gainsight.com' },
  { slug: 'totango', name: 'Totango', domain: 'totango.com' },
  { slug: 'churnzero', name: 'ChurnZero', domain: 'churnzero.com' },
  { slug: 'vitally', name: 'Vitally', domain: 'vitally.io' },
  // EdTech (new wave)
  { slug: 'edx', name: 'edX', domain: 'edx.org' },
  { slug: '2u', name: '2U', domain: '2u.com' },
  { slug: 'springboard', name: 'Springboard', domain: 'springboard.com' },
  { slug: 'udacity', name: 'Udacity', domain: 'udacity.com' },
  { slug: 'datacamp', name: 'DataCamp', domain: 'datacamp.com' },
  { slug: 'ixl', name: 'IXL Learning', domain: 'ixl.com' },
  { slug: 'instructure', name: 'Instructure', domain: 'instructure.com' },
  { slug: 'powerschool', name: 'PowerSchool', domain: 'powerschool.com' },
  { slug: 'bloomtech', name: 'BloomTech', domain: 'bloomtech.com' },
  { slug: 'quizlet', name: 'Quizlet', domain: 'quizlet.com' },
  { slug: 'varsitytutors', name: 'Varsity Tutors', domain: 'varsitytutors.com' },
  { slug: 'coursehero', name: 'Course Hero', domain: 'coursehero.com' },
  // Gaming / Interactive Entertainment
  { slug: 'ubisoft', name: 'Ubisoft', domain: 'ubisoft.com' },
  { slug: 'ea', name: 'Electronic Arts', domain: 'ea.com' },
  { slug: '2k', name: '2K Games', domain: '2k.com' },
  { slug: 'gearboxsoftware', name: 'Gearbox Software', domain: 'gearboxsoftware.com' },
  { slug: 'wizards', name: 'Wizards of the Coast', domain: 'wizards.com' },
  { slug: 'dapperlabs', name: 'Dapper Labs', domain: 'dapperlabs.com' },
  { slug: 'mythicalgames', name: 'Mythical Games', domain: 'mythicalgames.com' },
  { slug: 'immutablex', name: 'Immutable', domain: 'immutable.com' },
  { slug: 'skymavis', name: 'Sky Mavis', domain: 'skymavis.com' },
  // International Fintech
  { slug: 'adyen', name: 'Adyen', domain: 'adyen.com' },
  { slug: 'gocardless', name: 'GoCardless', domain: 'gocardless.com' },
  { slug: 'checkoutcom', name: 'Checkout.com', domain: 'checkout.com' },
  { slug: 'airwallex', name: 'Airwallex', domain: 'airwallex.com' },
  { slug: 'razorpay', name: 'Razorpay', domain: 'razorpay.com' },
  { slug: 'mollie', name: 'Mollie', domain: 'mollie.com' },
  { slug: 'rapyd', name: 'Rapyd', domain: 'rapyd.com' },
  { slug: 'n26', name: 'N26', domain: 'n26.com' },
  { slug: 'paysafe', name: 'Paysafe', domain: 'paysafe.com' },
  // Health (more)
  { slug: 'goodrx', name: 'GoodRx', domain: 'goodrx.com' },
  { slug: 'capsule', name: 'Capsule Pharmacy', domain: 'capsulecares.com' },
  { slug: 'thirtymadison', name: 'Thirty Madison', domain: 'thirtymadison.com' },
  { slug: 'nurx', name: 'Nurx', domain: 'nurx.com' },
  { slug: 'carbonhealth', name: 'Carbon Health', domain: 'carbonhealth.com' },
  { slug: 'commure', name: 'Commure', domain: 'commure.com' },
  { slug: 'crossoverhealth', name: 'Crossover Health', domain: 'crossoverhealth.com' },
  { slug: 'cotiviti', name: 'Cotiviti', domain: 'cotiviti.com' },
  // Testing / QA / DevOps
  { slug: 'browserstack', name: 'BrowserStack', domain: 'browserstack.com' },
  { slug: 'lambdatest', name: 'LambdaTest', domain: 'lambdatest.com' },
  { slug: 'smartbear', name: 'SmartBear', domain: 'smartbear.com' },
  { slug: 'applitools', name: 'Applitools', domain: 'applitools.com' },
  { slug: 'mabl', name: 'mabl', domain: 'mabl.com' },
  { slug: 'katalon', name: 'Katalon', domain: 'katalon.com' },
  { slug: 'saucelabs', name: 'Sauce Labs', domain: 'saucelabs.com' },
  // Commerce / Retail Tech
  { slug: 'bigcommerce', name: 'BigCommerce', domain: 'bigcommerce.com' },
  { slug: 'commercetools', name: 'commercetools', domain: 'commercetools.com' },
  { slug: 'vtex', name: 'VTEX', domain: 'vtex.com' },
  { slug: 'yotpo', name: 'Yotpo', domain: 'yotpo.com' },
  { slug: 'recharge', name: 'Recharge', domain: 'rechargepayments.com' },
  { slug: 'nacelle', name: 'Nacelle', domain: 'nacelle.com' },
  // HR / Recruiting Tech
  { slug: 'gem', name: 'Gem', domain: 'gem.com' },
  { slug: 'paradox', name: 'Paradox', domain: 'paradox.ai' },
  { slug: 'beamery', name: 'Beamery', domain: 'beamery.com' },
  { slug: 'eightfold', name: 'Eightfold AI', domain: 'eightfold.ai' },
  { slug: 'phenom', name: 'Phenom', domain: 'phenom.com' },
  // CX / Voice of Customer
  { slug: 'qualtrics', name: 'Qualtrics', domain: 'qualtrics.com' },
  { slug: 'medallia', name: 'Medallia', domain: 'medallia.com' },
  { slug: 'surveymonkey', name: 'SurveyMonkey', domain: 'surveymonkey.com' },
  { slug: 'dixa', name: 'Dixa', domain: 'dixa.com' },
  { slug: 'gladly', name: 'Gladly', domain: 'gladly.com' },
  // Manufacturing / Hardware
  { slug: 'fictiv', name: 'Fictiv', domain: 'fictiv.com' },
  { slug: 'xometry', name: 'Xometry', domain: 'xometry.com' },
  { slug: 'markforged', name: 'Markforged', domain: 'markforged.com' },
  { slug: 'carbon3d', name: 'Carbon', domain: 'carbon3d.com' },
  { slug: 'desktopmetal', name: 'Desktop Metal', domain: 'desktopmetal.com' },
  // Robotics / Defense Tech
  { slug: 'anduril', name: 'Anduril', domain: 'anduril.com' },
  { slug: 'shield-ai', name: 'Shield AI', domain: 'shield.ai' },
  { slug: 'agility-robotics', name: 'Agility Robotics', domain: 'agilityrobotics.com' },
  { slug: 'apptronik', name: 'Apptronik', domain: 'apptronik.com' },
  { slug: 'boston-dynamics', name: 'Boston Dynamics', domain: 'bostondynamics.com' },
  // Migrated from Lever
  { slug: 'airship', name: 'Airship', domain: 'airship.com' },
  { slug: 'betterment', name: 'Betterment', domain: 'betterment.com' },
  { slug: 'calm', name: 'Calm', domain: 'calm.com' },
  { slug: 'contentful', name: 'Contentful', domain: 'contentful.com' },
  { slug: 'fivetran', name: 'Fivetran', domain: 'fivetran.com' },
  { slug: 'hootsuite', name: 'Hootsuite', domain: 'hootsuite.com' },
  { slug: 'later', name: 'Later', domain: 'later.com' },
  { slug: 'masterclass', name: 'MasterClass', domain: 'masterclass.com' },
  { slug: 'pendo', name: 'Pendo', domain: 'pendo.io' },
  { slug: 'revel', name: 'Revel', domain: 'revel.xyz' },
  { slug: 'seatgeek', name: 'SeatGeek', domain: 'seatgeek.com' },
  { slug: 'sendbird', name: 'Sendbird', domain: 'sendbird.com' },
  { slug: 'smartsheet', name: 'Smartsheet', domain: 'smartsheet.com' },
  { slug: 'sproutsocial', name: 'Sprout Social', domain: 'sproutsocial.com' },
  { slug: 'typeform', name: 'Typeform', domain: 'typeform.com' },
  { slug: 'unbounce', name: 'Unbounce', domain: 'unbounce.com' },
  { slug: 'userflow', name: 'Userflow', domain: 'userflow.com' },
  { slug: 'walnut', name: 'Walnut', domain: 'walnut.io' },
  { slug: 'wrike', name: 'Wrike', domain: 'wrike.com' },
  // Verified-live expansion (AI, hardware, dev tools, SaaS)
  { slug: 'assemblyai', name: 'AssemblyAI', domain: 'assemblyai.com' },
  { slug: 'bandwidth', name: 'Bandwidth', domain: 'bandwidth.com' },
  { slug: 'bitwarden', name: 'Bitwarden', domain: 'bitwarden.com' },
  { slug: 'brave', name: 'Brave', domain: 'brave.com' },
  { slug: 'calendly', name: 'Calendly', domain: 'calendly.com' },
  { slug: 'cockroachlabs', name: 'Cockroach Labs', domain: 'cockroachlabs.com' },
  { slug: 'comet', name: 'Comet', domain: 'comet.com' },
  { slug: 'constantcontact', name: 'Constant Contact', domain: 'constantcontact.com' },
  { slug: 'customerio', name: 'Customer.io', domain: 'customer.io' },
  { slug: 'dashlane', name: 'Dashlane', domain: 'dashlane.com' },
  { slug: 'graphcore', name: 'Graphcore', domain: 'graphcore.ai' },
  { slug: 'labelbox', name: 'Labelbox', domain: 'labelbox.com' },
  { slug: 'mozilla', name: 'Mozilla', domain: 'mozilla.org' },
  { slug: 'prisma', name: 'Prisma', domain: 'prisma.io' },
  { slug: 'prolific', name: 'Prolific', domain: 'prolific.com' },
  { slug: 'proton', name: 'Proton', domain: 'proton.me' },
  { slug: 'singlestore', name: 'SingleStore', domain: 'singlestore.com' },
  { slug: 'speechmatics', name: 'Speechmatics', domain: 'speechmatics.com' },
  { slug: 'storyblok', name: 'Storyblok', domain: 'storyblok.com' },
  { slug: 'tenstorrent', name: 'Tenstorrent', domain: 'tenstorrent.com' },
  { slug: 'truefoundry', name: 'TrueFoundry', domain: 'truefoundry.com' },
  { slug: 'vonage', name: 'Vonage', domain: 'vonage.com' },
  { slug: 'yugabyte', name: 'Yugabyte', domain: 'yugabyte.com' },
  // Reputable expansion — enterprise SaaS, security, marketplaces (verified live)
  { slug: 'aftership', name: 'AfterShip', domain: 'aftership.com' },
  { slug: 'amwell', name: 'Amwell', domain: 'amwell.com' },
  { slug: 'apiiro', name: 'Apiiro', domain: 'apiiro.com' },
  { slug: 'boulevard', name: 'Boulevard', domain: 'joinblvd.com' },
  { slug: 'cameo', name: 'Cameo', domain: 'cameo.com' },
  { slug: 'carta', name: 'Carta', domain: 'carta.com' },
  { slug: 'chainguard', name: 'Chainguard', domain: 'chainguard.dev' },
  { slug: 'corelight', name: 'Corelight', domain: 'corelight.com' },
  { slug: 'cybereason', name: 'Cybereason', domain: 'cybereason.com' },
  { slug: 'dremio', name: 'Dremio', domain: 'dremio.com' },
  { slug: 'easyship', name: 'Easyship', domain: 'easyship.com' },
  { slug: 'epicgames', name: 'Epic Games', domain: 'epicgames.com' },
  { slug: 'fastspring', name: 'FastSpring', domain: 'fastspring.com' },
  { slug: 'godaddy', name: 'GoDaddy', domain: 'godaddy.com' },
  { slug: 'greenhouse', name: 'Greenhouse', domain: 'greenhouse.io' },
  { slug: 'guidde', name: 'Guidde', domain: 'guidde.com' },
  { slug: 'honeycomb', name: 'Honeycomb', domain: 'honeycomb.io' },
  { slug: 'hover', name: 'Hover', domain: 'hover.to' },
  { slug: 'ionos', name: 'IONOS', domain: 'ionos.com' },
  { slug: 'make', name: 'Make', domain: 'make.com' },
  { slug: 'netskope', name: 'Netskope', domain: 'netskope.com' },
  { slug: 'nextdoor', name: 'Nextdoor', domain: 'nextdoor.com' },
  { slug: 'onemedical', name: 'One Medical', domain: 'onemedical.com' },
  { slug: 'opentable', name: 'OpenTable', domain: 'opentable.com' },
  { slug: 'pantheon', name: 'Pantheon', domain: 'pantheon.io' },
  { slug: 'platformsh', name: 'Platform.sh', domain: 'platform.sh' },
  { slug: 'pubnub', name: 'PubNub', domain: 'pubnub.com' },
  { slug: 'quillbot', name: 'QuillBot', domain: 'quillbot.com' },
  { slug: 'route', name: 'Route', domain: 'route.com' },
  { slug: 'sendcloud', name: 'Sendcloud', domain: 'sendcloud.com' },
  { slug: 'sezzle', name: 'Sezzle', domain: 'sezzle.com' },
  { slug: 'shopmonkey', name: 'Shopmonkey', domain: 'shopmonkey.io' },
  { slug: 'similarweb', name: 'Similarweb', domain: 'similarweb.com' },
  { slug: 'stockx', name: 'StockX', domain: 'stockx.com' },
  { slug: 'sumologic', name: 'Sumo Logic', domain: 'sumologic.com' },
  { slug: 'super', name: 'Super', domain: 'super.com' },
  { slug: 'tia', name: 'Tia', domain: 'asktia.com' },
  { slug: 'veracode', name: 'Veracode', domain: 'veracode.com' },
  { slug: 'wallapop', name: 'Wallapop', domain: 'wallapop.com' },
  { slug: 'wikimedia', name: 'Wikimedia Foundation', domain: 'wikimedia.org' },
  { slug: 'wolt', name: 'Wolt', domain: 'wolt.com' },
  { slug: 'workato', name: 'Workato', domain: 'workato.com' },
  { slug: 'zocdoc', name: 'Zocdoc', domain: 'zocdoc.com' },
  { slug: 'zscaler', name: 'Zscaler', domain: 'zscaler.com' },
  { slug: 'zuora', name: 'Zuora', domain: 'zuora.com' },
  { slug: 'zwift', name: 'Zwift', domain: 'zwift.com' },
  // Reputable expansion — fintech & crypto (verified live)
  { slug: 'alloy', name: 'Alloy', domain: 'alloy.com' },
  { slug: 'bitso', name: 'Bitso', domain: 'bitso.com' },
  { slug: 'blockchain', name: 'Blockchain.com', domain: 'blockchain.com' },
  { slug: 'bybit', name: 'Bybit', domain: 'bybit.com' },
  { slug: 'consensys', name: 'ConsenSys', domain: 'consensys.io' },
  { slug: 'fireblocks', name: 'Fireblocks', domain: 'fireblocks.com' },
  { slug: 'groww', name: 'Groww', domain: 'groww.in' },
  { slug: 'okx', name: 'OKX', domain: 'okx.com' },
  { slug: 'ozow', name: 'Ozow', domain: 'ozow.com' },
  { slug: 'phonepe', name: 'PhonePe', domain: 'phonepe.com' },
  { slug: 'prove', name: 'Prove', domain: 'prove.com' },
  { slug: 'sumup', name: 'SumUp', domain: 'sumup.com' },
  { slug: 'tamara', name: 'Tamara', domain: 'tamara.co' },
  { slug: 'truelayer', name: 'TrueLayer', domain: 'truelayer.com' },
  // More SaaS
  { slug: 'pipedrive', name: 'Pipedrive', domain: 'pipedrive.com' },
  { slug: 'copper', name: 'Copper CRM', domain: 'copper.com' },
  { slug: 'kustomer', name: 'Kustomer', domain: 'kustomer.com' },
  { slug: 'gorgias', name: 'Gorgias', domain: 'gorgias.com' },
  { slug: 'gainsight', name: 'Gainsight', domain: 'gainsight.com' },
  { slug: 'churnzero', name: 'ChurnZero', domain: 'churnzero.com' },
  { slug: 'chorus', name: 'Chorus.ai', domain: 'chorus.ai' },
  { slug: 'clari', name: 'Clari', domain: 'clari.com' },
];

export async function fetchAllGreenhouseJobs(): Promise<Job[]> {
  const seen = new Set<string>();
  const unique = GREENHOUSE_COMPANIES.filter(c => {
    if (seen.has(c.slug)) return false;
    seen.add(c.slug);
    return true;
  });
  const results = await Promise.allSettled(
    unique.map(c => fetchGreenhouseJobs(c.slug, c.name, c.domain, c.batch))
  );
  return results.flatMap(r => (r.status === 'fulfilled' ? r.value : []));
}
